#!/usr/bin/env python3
"""Render the immutable GHCR deployment: a Caddyfile + docker-compose.yaml.

Consumes the ``image-lock.json`` produced by ``build_images.py publish`` (all
six images pinned by ``@sha256:`` digest) and emits, into the tracked
``daytona/deploy/`` (with a copy of the lock):

  * ``Caddyfile``        — a path router on :8080 that strips each service's path
                           prefix to ``/mcp`` and reverse-proxies to the right
                           internal upstream (streaming-safe).
  * ``docker-compose.yaml`` — six MCP-only services (no host ports, data baked
                           into each image, NO volumes) + one Caddy front door
                           binding :8080 and mounting only the Caddyfile.
  * ``images.env``       — copied/linked digest refs the compose interpolates.

Design rules (per the deployment contract):
  * Images are referenced by digest via ``${PM_IMAGE:?...}`` etc.; a missing env
    var fails compose closed.
  * Child services expose only their internal MCP port (expose:), never a host
    port. Only Caddy publishes a host port (:8080).
  * No bind mounts for data — it is baked into each image layer.
  * Caddy image is an explicit pinned tag (never :latest); the operator may
    override it, and ``docker compose pull`` resolves it to a digest locally.
  * ``/health`` returns a static JSON describing the routing contract — it does
    NOT proxy downstream, so it never falsely claims all servers are healthy.

Pure stdlib; no network, no Docker calls.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional

import contract
from contract import CADDY_PORT, IMAGE_ENV_BY_KEY, SERVICES

DEPLOY_DIR = Path(__file__).resolve().parents[1] / "deploy"


class DeployError(Exception):
    pass


# --------------------------------------------------------------------------- #
# Caddyfile                                                                   #
# --------------------------------------------------------------------------- #
def render_caddyfile() -> str:
    """Render the :8080 path router.

    For each service, every path prefix (primary + aliases) is handled with
    ``handle_path`` (which strips the matched prefix) and then the request is
    rewritten to ``/mcp`` before being proxied to ``<service>:<port>``.

    ``flush_interval -1`` disables response buffering so FastMCP's streamable
    HTTP / SSE responses are forwarded immediately. The upstream ``Host`` header
    is pinned to the upstream host:port so FastMCP's DNS-rebinding/Host checks
    see a stable, expected value (origin protection is also disabled in-image).
    """
    lines: List[str] = []
    lines.append("# GENERATED by daytona/images/gen_deploy.py — do not edit by hand.")
    lines.append("# Single front door for the six Enterprise-Bench MCP servers.")
    lines.append("{")
    lines.append("\tadmin off")
    lines.append("\t# No automatic HTTPS: this is an internal reverse proxy fronted")
    lines.append("\t# by the sandbox/preview layer which terminates TLS.")
    lines.append("\tauto_https off")
    lines.append("}")
    lines.append("")
    lines.append(f":{CADDY_PORT} {{")

    for service in SERVICES:
        upstream = f"{service.key}:{service.mcp_port}"
        prefixes = [service.route, *service.route_aliases]
        pretty = ", ".join(prefixes)
        lines.append(f"\t# {service.config_name} -> {upstream}  (prefixes: {pretty})")
        for prefix in prefixes:
            # handle_path strips the matched prefix; we then set the path to the
            # single MCP route. Match both "/pm" and "/pm/*".
            #
            # The upstream FastMCP streamable-HTTP server mounts exactly ONE
            # endpoint at MCP_ROUTE ("/mcp") and 404s any sub-path. The harness
            # always calls "<base><prefix>/mcp" (see routed_config.py /
            # mcp.json), so after handle_path strips "<prefix>" the residual
            # path is already "/mcp". We therefore rewrite to a FIXED
            # MCP_ROUTE — NOT "{MCP_ROUTE}{path}", which would re-append the
            # stripped "/mcp" and proxy "/mcp/mcp" upstream (-> 404).
            lines.append(f"\thandle_path {prefix}/* {{")
            lines.append(f"\t\trewrite * {contract.MCP_ROUTE}")
            lines.append("\t\treverse_proxy " + upstream + " {")
            lines.append("\t\t\tflush_interval -1")
            lines.append(f"\t\t\theader_up Host {upstream}")
            lines.append("\t\t}")
            lines.append("\t}")
            lines.append(f"\thandle {prefix} {{")
            lines.append(f"\t\trewrite * {contract.MCP_ROUTE}")
            lines.append("\t\treverse_proxy " + upstream + " {")
            lines.append("\t\t\tflush_interval -1")
            lines.append(f"\t\t\theader_up Host {upstream}")
            lines.append("\t\t}")
            lines.append("\t}")
        lines.append("")

    # Routing-contract health endpoint (NOT a downstream health aggregation).
    routes = {
        s.config_name: {
            "prefix": s.route,
            "aliases": list(s.route_aliases),
            "upstream": f"{s.key}:{s.mcp_port}",
            "mcp_path": contract.MCP_ROUTE,
        }
        for s in SERVICES
    }
    health_body = json.dumps(
        {
            "status": "router-ok",
            "note": "This reports the Caddy routing contract only; it does NOT "
                    "probe downstream MCP servers.",
            "routes": routes,
        },
        separators=(",", ":"),
    ).replace("\\", "\\\\").replace('"', '\\"')
    lines.append("\t# Routing-contract identity (does not probe downstream health).")
    lines.append("\thandle /health {")
    lines.append("\t\theader Content-Type application/json")
    lines.append(f'\t\trespond "{health_body}" 200')
    lines.append("\t}")
    lines.append("")
    lines.append("\t# Root: plain description, no external fetches.")
    lines.append("\thandle / {")
    lines.append('\t\trespond "Enterprise-Bench MCP router. See /health for routes." 200')
    lines.append("\t}")
    lines.append("")
    lines.append("\t# Anything else is an unknown route.")
    lines.append("\thandle {")
    lines.append('\t\trespond "Not found" 404')
    lines.append("\t}")
    lines.append("}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# docker-compose.yaml                                                         #
# --------------------------------------------------------------------------- #
def render_compose(caddy_image: str) -> str:
    """Render the MCP-only compose. Images come from ${*_IMAGE} env (digest refs
    from images.env); a missing var fails closed via the ``:?`` form."""
    lines: List[str] = []
    lines.append("# GENERATED by daytona/images/gen_deploy.py — do not edit by hand.")
    lines.append("# MCP-only deployment: six digest-pinned servers behind one Caddy router.")
    lines.append("# Data is baked into each image (no volumes). Only Caddy exposes a host port.")
    lines.append("services:")

    for service in SERVICES:
        env_var = IMAGE_ENV_BY_KEY[service.key]
        lines.append(f"  {service.key}:")
        lines.append(
            f'    image: ${{{env_var}:?set {env_var} from images.env (digest-pinned)}}'
        )
        lines.append(f"    container_name: bench-ghcr-{service.key}")
        # MCP-only: the image default CMD already runs mcp_server.py.
        lines.append("    restart: unless-stopped")
        lines.append("    expose:")
        lines.append(f'      - "{service.mcp_port}"')
        lines.append("    environment:")
        lines.append('      - "DATA_DIR=/data"')
        lines.append(f'      - "MCP_PORT={service.mcp_port}"')
        lines.append('      - "FASTMCP_HTTP_HOST_ORIGIN_PROTECTION=false"')
        lines.append("    healthcheck:")
        # TCP connect to the local MCP port; no secrets, no label leakage.
        lines.append(
            '      test: ["CMD", "python", "-c", '
            '"import socket,sys; s=socket.socket(); '
            "s.settimeout(3); sys.exit(0 if "
            f"s.connect_ex(('127.0.0.1',{service.mcp_port}))==0 else 1)\"]"
        )
        lines.append("      interval: 10s")
        lines.append("      timeout: 5s")
        lines.append("      retries: 5")
        lines.append("      start_period: 15s")
        lines.append("")

    # Caddy front door.
    lines.append("  caddy:")
    lines.append(f"    image: {caddy_image}")
    lines.append("    container_name: bench-ghcr-caddy")
    lines.append("    restart: unless-stopped")
    lines.append("    ports:")
    lines.append(f'      - "{CADDY_PORT}:{CADDY_PORT}"')
    lines.append("    volumes:")
    lines.append("      - ./Caddyfile:/etc/caddy/Caddyfile:ro")
    lines.append("    depends_on:")
    for service in SERVICES:
        lines.append(f"      {service.key}:")
        lines.append("        condition: service_healthy")
    lines.append("")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# Lock consumption                                                            #
# --------------------------------------------------------------------------- #
def _load_lock(path: Path) -> Dict:
    if not path.is_file():
        raise DeployError(f"image lock not found: {path}")
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError:
        raise DeployError("image lock is not valid JSON.")
    images = data.get("images")
    if not isinstance(images, dict):
        raise DeployError("image lock missing 'images' map.")
    missing = [s.key for s in SERVICES if s.key not in images]
    if missing:
        raise DeployError(f"image lock missing services: {', '.join(missing)}")
    for key, entry in images.items():
        digest = entry.get("digest", "")
        if not (isinstance(digest, str) and digest.startswith("sha256:") and len(digest) == 71):
            raise DeployError(f"image lock service '{key}' has no valid sha256 digest.")
    return data


def _render_images_env(lock: Dict) -> str:
    lines = [
        "# GENERATED by gen_deploy.py from image-lock.json — digest-pinned refs.",
        f"# release={lock.get('release')} owner={lock.get('owner')}",
    ]
    for service in SERVICES:
        entry = lock["images"][service.key]
        lines.append(f"{IMAGE_ENV_BY_KEY[service.key]}={entry['pinned_ref']}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# CLI                                                                         #
# --------------------------------------------------------------------------- #
def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"[deploy] wrote {path}")


def main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog="gen_deploy.py",
        description="Render Caddyfile + docker-compose.yaml from an image lock.",
    )
    p.add_argument("--image-lock", type=Path, default=DEPLOY_DIR / "image-lock.json",
                   help="image-lock.json from `build_images.py publish` "
                        "(default: the tracked daytona/deploy/image-lock.json).")
    p.add_argument("--out-dir", type=Path, default=DEPLOY_DIR,
                   help="Output directory (default: daytona/deploy).")
    p.add_argument("--caddy-image", default=contract.CADDY_IMAGE,
                   help=f"Caddy image (explicit pinned tag; default {contract.CADDY_IMAGE}). "
                        "Never :latest; resolved to a digest by `docker compose pull`.")
    args = p.parse_args(argv)

    try:
        lock = _load_lock(args.image_lock)
        if args.caddy_image.strip().endswith(":latest") or ":" not in args.caddy_image:
            raise DeployError(
                "--caddy-image must be an explicit non-latest tag (e.g. "
                "caddy:2.10.2-alpine); a floating/latest tag is refused."
            )
        out_dir = args.out_dir
        lock_out = out_dir / "image-lock.json"
        if args.image_lock.resolve() != lock_out.resolve():
            _write(lock_out, json.dumps(lock, indent=2) + "\n")
        _write(out_dir / "Caddyfile", render_caddyfile())
        _write(out_dir / "docker-compose.yaml", render_compose(args.caddy_image))
        _write(out_dir / "images.env", _render_images_env(lock))
        print(f"[deploy] deploy with:  docker compose --env-file images.env up -d  "
              f"(from {out_dir})")
        print(f"[deploy] router will listen on :{CADDY_PORT}")
        return 0
    except DeployError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
